### ISSUE TITLE
Let Hydra manage build machines

### ISSUE THREAD

**Issue by copumpkin** [NixOS/hydra#201]
It would be lovely if hydra itself knew how to deploy more build machines (perhaps using NixOps). Then if things were running slowly and I was feeling rich, I could tell to spin up a few C4.8xlarges on EC2, blast through nixpkgs in a few hours, then shut them down again.

Basically, a facility for scaling on demand would be amazing.

**Comment by edolstra** [comment]
I'm working on a auto-scaling tool at the moment. The queue runner already exports info about how many runnable build steps exist for each system type (d571e44b86f8b166d835f6fd413fbf612dda8e26), which can be used by the provisioner tool to fire up build machines.

**Comment by copumpkin** [comment]
Awesome! Very exciting :+1: :+1: :beers: etc.

**Comment by edolstra** [comment]
First version: https://github.com/NixOS/hydra-provisioner

**Comment by copumpkin** [comment]
Wonderful, thanks! So you're actually using some EC2 for hydra? I always assumed they were physical machines due to VM tests etc.

**Comment by edolstra** [comment]
It's physical machines at TU Delft, plus some VMs donated by Rackspace. But now we can use the Hydra provisioner to spin up EC2 instances to burn through the queue quickly. I've been running it since yesterday with up to 12 EC2 spot instances. Indeed VM tests can't run on EC2, so currently the queue mostly consists of VM tests :-)

**Comment by copumpkin** [comment]
Should I mark this as closed?

**Comment by edolstra** [comment]
Sure.
