### ISSUE TITLE
Discussion: Hydra development

### ISSUE THREAD

**Issue by rbvermaa** [NixOS/hydra#218]
This ticket is meant for discussing some bigger features that various people are planning, and to coordinate efforts, make sure no duplicate work is done etc.

I will try to summarize the features in the top post, as soon as they are posted/crystalized in the thread. We should create new issues, once we settle on a feature.

**Comment by shlevy** [comment]
Was about to claim #140, but I see @edolstra beat me to it :smile: No other features pop out at me currently.

**Comment by peti** [comment]
I would like to see (and participate in) an effort to decentralize the infrastructure that provides binary packages. I care about this issue because of my experiences running `hydra.cryp.to`. That server builds all Haskell packages before I push an Nixpkgs update to `master`. This means that when the Haskell package set in `master` is updated, Linux/x86_64 binaries for every single one of those packages are available for download from `hydra.cryp.to` already.

`hydra.nixos.org`, however, doesn't know this and doesn't take advantage of the fact. Consequently, `hydra.nixos.org` evaluates stuff for a couple of hours until it reaches Nixpkgs, eventually, and then it starts building all those Haskell packages *again*. Users of `hydra.nixos.org` can download Haskell binaries some 1-2 days after the update was pushed to `master`, but no earlier --- despite the fact that binaries would have been readily available the entire time.

Now, the current architecture has no good solution for this issue. We could set up some mechanism that pushes the binaries from `hydra.cryp.to` to `hydra.nixos.org`. Maybe a cron job on `hydra.nixos.org` could pull the appropriate manifest from the other server once an hour, or something like that. It's not a great solution, but it's feasible.

But then ... we're not just talking about `hydra.cryp.to`. There is any number of machines out there that have binaries for a large subset of Nixpkgs way sooner than `hydra.nixos.org` does. How do we take advantage of those? The current centralized architecture assumes that `hyda.nixos.org` is somehow aware of all of those servers, downloads all the packages from them, and then stores them locally until garbage collection comes.

A more scalable approach would be one where `hydra.nixos.org` acts like a tracker in Bittorrent does: every machine can register the contents of its Nix store with `hydra.nixos.org`, and then users can talk to `hydra.nixos.org` and ask: do you have binaries for `/nix/store/deadbeef...-foo-1.0`? The response to that query would not be a binary, but instead it would be the set of machines that have advertised that particular store path for download so that the client can download it directly from them.

**Comment by benley** [comment]
Really, ideal would be if hydra.nixos.org had enough builder resources behind it that it could run all those builds and obviate the complexity of establishing trust relationships between operators of all the different hydra instances. That becomes mostly an issue of funding, of course.

**Comment by edolstra** [comment]
Yeah, I agree the trust issue would be really tricky (trusting `hydra.nixos.org` would implicitly require trusting `hydra.cryp.to` and any other Hydra instances it's pulling from). Maybe it could be done by only trusting binaries that have multiple signatures.

I'm currently working on a new hydra-queue-runner that would remove the need for a central Nix store. Rather, the build machines would upload their build results directly to a binary cache in an S3 bucket. That way, the central Hydra server (the one running hydra-evaluator and hydra-queue-runner) wouldn't need nearly as much disk space and could be moved to a fast SSD disk (ensuring that hydra-evaluator is really fast). That should help a lot.

**Comment by peti** [comment]
The list of trusted servers has to be configured explicitly, i.e. it has to be possible to specify a set of public keys that can authenticate binaries the user will trust (and download). Therefore, if someone trusts no any binaries except those built by `hydra.nixos.org`, he or she will not download anything except those binaries from `hydra.nixos.org`.

It's important to realize that A trust B and B trusts C does not imply that A trust C. If a user trusts only `hydra.nixos.org` and that machine downloads a binary from `hydra.cryp.to` (because it trusts it), then this user will *not* download those binaries because he or she doesn't trust `hydra.cryp.to`.

This phenomenon gives rise to a web of trust model, where users can say that they trust `hydra.cryp.to` to act as a certification authority, of sorts, i.e. users can configure Nix to download all binaries from `hydra.nixos.org` -- regardless of where these were built --, thereby effectively trusting everyone that `hydra.nixos.org` trusts.

IMHO, this explicit trust model is a huge improvement over what he have now -- which is effectively no trust model at all.

**Comment by nckx** [comment]
> This phenomenon gives rise to a web of trust model, where users can say that they trust hydra.nixos.org to act as a certification authority, of sorts, i.e. users can configure Nix to download all binaries from hydra.nixos.org -- regardless of where these were built --, thereby effectively trusting everyone that hydra.nixos.org trusts.

Since the only reason to copy binaries to hydra.nixos.org would be to use them as build inputs to something greater (simple mirroring aside), no other trust model really makes sense.

**Comment by domenkozar** [comment]
@edolstra that's good news.

**Comment by domenkozar** [comment]
Very relevant is recent frontend proposal: https://github.com/NixOS/hydra/issues/314

**Comment by gilligan** [comment]
Since this was for discussion only and inactive for years i'll go ahead and close.
