### ISSUE TITLE
Display S3 download link for products

### ISSUE THREAD

**Issue by domenkozar** [NixOS/hydra#321]
It's very inconvenient that S3 backed hydra doesn't serve files for installing Nix.

Example page: http://hydra.nixos.org/build/36401064

This issue was raised in https://github.com/NixOS/nix/issues/891

**Comment by globin** [comment]
This is implemented but probably not used due to the `store_mode` not being set anymore due to the use of the new `store_uri`: https://github.com/NixOS/hydra/blob/master/src/lib/Hydra/Controller/Build.pm#L225-L244

This isn't possible to achieve on current master as the `hydra-queue-runner` will error out on `store_mode` being set, we are running a hydra now with a patch to only warn (https://github.com/mayflower/hydra/commit/6216eeb7d9b3de922100f2afebc2b5e11aac6726)

**Comment by domenkozar** [comment]
Fixed in https://github.com/NixOS/hydra/commit/42fbde03835b90c52e630ed0c2211217e2f77181
