### ISSUE TITLE
hydra-evaluator is single threaded

### ISSUE THREAD

**Issue by expipiplus1** [NixOS/hydra#345]
The `hydra-evaluator` service seems to be very slow.

When I make a push to a repo with lots of dependent projects, these are all triggered at once, there are 14 projects. `hydra-evaluator` takes several minutes to examine all of these jobsets. I'm a little surprised that it takes such a long time to instantiate 14 not very complex expressions whose remote sources have already been fetched.

**Comment by domenkozar** [comment]
It has to fetch all inputs, which may be many git repositories and then evaluate all nix expressions. Help to have a good connection line and SSD.

**Comment by expipiplus1** [comment]
@domenkozar Does it use the cached inputs at all? Is the code in the evaluator which does the `git fetch` parallelised?

I imagine that it would be a large win to ping remote inputs in parallel, seeing as it's such a high latency operation. 

Another option would be to only fetch new inputs (from github) after a `push` webhook has been triggered.

**Comment by Ericson2314** [comment]
Hydra should in general be more push-based, I believe.

**Comment by domenkozar** [comment]
@expipiplus1 hard to say which part is being slow.

https://github.com/NixOS/hydra/pull/378 might help, that improved it a lot for me .

Otherwise I agree hydra-evaluator needs some threading, but last time I talked with @edolstra he said it's not an easy thing to do.

**Comment by edolstra** [comment]
More info is needed here to be able to tell whether multi-threading would help. A multi-process hydra-evaluator would not be hard to do, I believe. But if you're I/O limited that's not going to help much either.

**Comment by domenkozar** [comment]
In Snabb case it would help a lot.

If you look at following evaluations, they all happened because of a single git repository update.

![2016-08-26-174943_972x479_scrot](https://cloud.githubusercontent.com/assets/126339/18011442/82722064-6bb5-11e6-8100-70f737d7fd84.png)

It's still in progress, it will take more than an hour to evaluate all of them.

Here is CPU usage (see 1 core utilization at the end for the last hour) for today:

![2016-08-26-175100_511x383_scrot](https://cloud.githubusercontent.com/assets/126339/18011502/c15b4576-6bb5-11e6-973e-c43d74972dc5.png)

**Comment by edolstra** [comment]
I did some work on multi-threaded evaluation: https://github.com/edolstra/nix/commit/3ad4128f67b16a797e074576c0458d118cf443f6

However, in the case of Hydra, it's easier to make `hydra-evaluator` multi-process. (It already forks a child process to handle each jobset, but does so synchronously. The only reason not to run children in parallel is because the SCM cache would need some locking.)

**Comment by domenkozar** [comment]
This is done as of https://github.com/NixOS/hydra/commit/e0b2921ff2f714fd243a4ef3357c5d01fffba1a5
