### ISSUE TITLE
Timeout killed still-building ceph build

### ISSUE THREAD

**Issue by nagy** [NixOS/hydra#845]
I recently made pullrequest to nixpkgs (https://github.com/NixOS/nixpkgs/pull/108396) where I enabled the `aarch64-linux` platform for `ceph`. Since then, a hydra build has started (https://hydra.nixos.org/build/135138392/)

However, it ran into a timeout of 10h while it was still building at around 74%, as you can see here: https://hydra.nixos.org/build/135138409/nixlog/1/tail

These long build times are normal for ceph on aarch64. On a raspberry pi 4 such a build takes about half a day.

I understand that this can be seen as a burden on the buildserver, but is it possible to make an exception for this package, since it was still building fine? I am confident that it would pass if given a bit more time.

One more Link:

A filter for ceph in a recent evaluation:
https://hydra.nixos.org/eval/1642367?filter=ceph&compare=1642303&full=#tabs-now-fail

**Comment by samueldr** [comment]
I *think* it would be helped with `requiredSystemFeatures = [ "big-parallel" ];`.

I'm not sure what ended up being the resolution of a discussion in the past, and if it would still be the case, but we might have some of our aarch64 machines being oversold a bit, which *may* be bringing their I/O latency up through the roof. So builds with a lot of files like this can end up timing out, where they would go through quickly enough otherwise. [4 hours is feasible](https://hydra.nixos.org/build/134780415).

**Comment by nagy** [comment]
If the aarch64 machines are overburdened, wouldn't a `big-parallel` make the situation worse?
Also, since this is only an aarch64 issue, I am not sure if we should change the package for that since the x86_64 build runs just fine.

I am unware, do these hydra builds restart eventually? Because maybe in the future the machines are a little bit less taxed and the build runs through.

**Comment by samueldr** [comment]
The `big-parallel` machines are configured differently. So when the build is sent to a machine, it would be sent *only* to a `big-parallel` machine.

Builds are not restarted automatically. It needs human intervention.

**Comment by nagy** [comment]
With a recent evaluation , ceph has built now https://hydra.nixos.org/eval/1643412?filter=ceph&compare=1643400&full=

Thank you
