### ISSUE TITLE
some eval-wide actions don't work anymore

### ISSUE THREAD

**Issue by vcunat** [NixOS/hydra#861]
Example:
https://hydra.nixos.org/eval/1646203/restart-failed
```
Caught exception in Hydra::Controller::JobsetEval->restart_failed "Can't locate object method "project" via package "Hydra::Model::DB::JobsetEvals" at /nix/store/6l4xbx5dfv3dgm2nqiw1437win551kn0-hydra-0.1.20210130.aaf16d5/libexec/hydra/lib/Hydra/Controller/JobsetEval.pm line 155."
```
I also noticed the same for `/bump`.  These two actions certainly worked on Hydra.nixos.org until recently.

**Comment by samueldr** [comment]
Sounds like #855 ?

**Comment by vcunat** [comment]
Sounds likely, now that I look at the diff.  I only inspected descriptions and commit messages of recent PRs and issues.

**Comment by grahamc** [comment]
I’ll merge and deploy that today. Sorry for the bug, and the delay. 

On February 2, 2021, GitHub <notifications@github.com> wrote:
> Sounds likely, now that I look at the diff. I only inspected
> descriptions and commit messages of recent PRs and issues.
>

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/NixOS/hydra/issues/861#issuecomment-771492068>, or

unsubscribe <https://github.com/notifications/unsubscribe-
auth/AAASXLG5S4IOV6TQPHXJJHTS467VDANCNFSM4W6G5XKA>.

**Comment by vcunat** [comment]
Seems fixed on Hydra.nixos.org.
