### ISSUE TITLE
The testsuite never checks what happens when `destStore != localStore`

### ISSUE THREAD

**Issue by regnat** [NixOS/hydra#938]
Hydra distinguishes between the “local store” (the one on which the evaluation takes place) and the “destination store” (the one to which all the build outputs are sent). However in the test suite both these stores are the same one, which might hide some logic errors (caused me some surprise in https://github.com/NixOS/hydra/pull/875 for example).

This could be fixed for example by setting `store_uri = file:/some/where` in the hydra config used for the tests.

**Comment by grahamc** [comment]
It would be great if you could submit such a test!

On April 28, 2021, GitHub ***@***.***> wrote:
> Hydra distinguishes between the “local store” (the one on which the
> evaluation takes place) and the “destination store” (the one to which
> all the build outputs are sent). However in the test suite both these
> stores are the same one, which might hide some logic errors (caused me
> some surprise in #875 <https://github.com/NixOS/hydra/pull/875> for
> example).
>
> This could be fixed for example by setting store_uri =
> file:/some/where in the hydra config used for the tests.
>

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/NixOS/hydra/issues/938>, or unsubscribe
<https://github.com/notifications/unsubscribe-
auth/AAASXLCEVAFZIBL74DUMOQDTK7DLXANCNFSM43WTS34Q>.

**Comment by regnat** [comment]
> It would be great if you could submit such a test!

Just in case you missed it, the PR is already there (#940), but it's stuck atm because it breaks a test and I'm not sure how to fix it
